name = "afk-router"
main = "worker.js"
compatibility_date = "2025-01-14"

# Routes configuration for probelabs.com subdirectory
[[routes]]
pattern = "probelabs.com/afk"
zone_name = "probelabs.com"

[[routes]]
pattern = "probelabs.com/afk/*"
zone_name = "probelabs.com"